---
# tasks file for myrole
  - name: Web-server install.
    apt: 
      name: nginx={{ nginx_version }}
      state: present
      
  - name: Create test page
    import_tasks: create_web_page.yml   

  - name: Open tcp
    import_tasks: open_tcp.yml        

  - name: Check web-page 
    uri:
      url: "http://{{ ansible_facts.all_ipv4_addresses[0] }}"